// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxqKy7IvT2ZKz70RtRvQW18RA4ZE0zNqw',
    appId: '1:409626674437:web:37decd4d999af08ad3236c',
    messagingSenderId: '409626674437',
    projectId: 'whss-flutter-demo',
    authDomain: 'whss-flutter-demo.firebaseapp.com',
    storageBucket: 'whss-flutter-demo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXlh5PnuaeQu7EdUUm3W9IWRfyWusUzYM',
    appId: '1:409626674437:ios:815711bf2147c345d3236c',
    messagingSenderId: '409626674437',
    projectId: 'whss-flutter-demo',
    storageBucket: 'whss-flutter-demo.appspot.com',
    iosBundleId: 'com.example.projectWhssApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXlh5PnuaeQu7EdUUm3W9IWRfyWusUzYM',
    appId: '1:409626674437:ios:c87bf4a4f59a0a0cd3236c',
    messagingSenderId: '409626674437',
    projectId: 'whss-flutter-demo',
    storageBucket: 'whss-flutter-demo.appspot.com',
    iosBundleId: 'com.example.projectWhssApp.RunnerTests',
  );
}
